export const SAVE_RESULTS = "SAVE_RESULTS";
export const SET_SELECTED_JOB = "SET_SELECTED_JOB";
export const SET_LOCATION_NAME = "SET_LOCATION_NAME";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
export const SET_ERROR_FORM = "SET_ERROR_FORM";
export const CLEAN_ERROR = "CLEAN_ERROR";